
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frmUserRol
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frmUserRol
			this.Name = "Hotel.frmUserRol";
			this.Title = global::Mono.Unix.Catalog.GetString("frmUserRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
