
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frmRoles
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtRol;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwRoles;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Entry txtBuscarRol;

		private global::Gtk.Button btnCancelar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frmRoles
			this.Name = "Hotel.frmRoles";
			this.Title = global::Mono.Unix.Catalog.GetString("frmRoles");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Hotel.frmRoles.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Rol:");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w1.X = 54;
			w1.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtRol = new global::Gtk.Entry();
			this.txtRol.WidthRequest = 250;
			this.txtRol.CanFocus = true;
			this.txtRol.Name = "txtRol";
			this.txtRol.IsEditable = true;
			this.txtRol.InvisibleChar = '•';
			this.fixed1.Add(this.txtRol);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtRol]));
			w2.X = 100;
			w2.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w3.X = 300;
			w3.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.btnModificar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnModificar]));
			w4.X = 148;
			w4.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGuardar]));
			w5.X = 78;
			w5.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Configuraciones de Roles de Usuarios");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w6.X = 90;
			w6.Y = 27;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 380;
			this.GtkScrolledWindow.HeightRequest = 250;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwRoles = new global::Gtk.TreeView();
			this.tvwRoles.CanFocus = true;
			this.tvwRoles.Name = "tvwRoles";
			this.GtkScrolledWindow.Add(this.tvwRoles);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w8.X = 23;
			w8.Y = 192;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnBuscar]));
			w9.X = 334;
			w9.Y = 160;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscarRol = new global::Gtk.Entry();
			this.txtBuscarRol.CanFocus = true;
			this.txtBuscarRol.Name = "txtBuscarRol";
			this.txtBuscarRol.IsEditable = true;
			this.txtBuscarRol.WidthChars = 36;
			this.txtBuscarRol.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscarRol);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscarRol]));
			w10.X = 30;
			w10.Y = 160;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancelar]));
			w11.X = 228;
			w11.Y = 105;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 422;
			this.DefaultHeight = 450;
			this.Show();
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.btnModificar.Clicked += new global::System.EventHandler(this.OnBtnModificarClicked);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.tvwRoles.CursorChanged += new global::System.EventHandler(this.OnTvwRolesCursorChanged);
			this.btnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
			this.btnCancelar.Clicked += new global::System.EventHandler(this.OnBtnCancelarClicked);
		}
	}
}
