
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frmGestionHabitaciones
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Entry txtNoHab;

		private global::Gtk.Button btnAñadirHab;

		private global::Gtk.Button btnEliminarHab;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.ScrolledWindow vwTablaHab;

		private global::Gtk.TreeView tvwHabitaciones;

		private global::Gtk.ComboBox cbxDescripcHab;

		private global::Gtk.Entry txtBuscar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frmGestionHabitaciones
			this.Name = "Hotel.frmGestionHabitaciones";
			this.Title = global::Mono.Unix.Catalog.GetString("frmGestionHabitaciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Hotel.frmGestionHabitaciones.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Gestiones de Habitaciones");
			this.fixed2.Add(this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
			w1.X = 121;
			w1.Y = 17;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Numero de Habitacion:");
			this.fixed2.Add(this.label4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
			w2.X = 31;
			w2.Y = 50;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion Habitacion:");
			this.fixed2.Add(this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
			w3.X = 30;
			w3.Y = 90;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtNoHab = new global::Gtk.Entry();
			this.txtNoHab.CanFocus = true;
			this.txtNoHab.Name = "txtNoHab";
			this.txtNoHab.IsEditable = true;
			this.txtNoHab.InvisibleChar = '•';
			this.fixed2.Add(this.txtNoHab);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtNoHab]));
			w4.X = 194;
			w4.Y = 48;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnAñadirHab = new global::Gtk.Button();
			this.btnAñadirHab.CanFocus = true;
			this.btnAñadirHab.Name = "btnAñadirHab";
			this.btnAñadirHab.UseUnderline = true;
			this.btnAñadirHab.Label = global::Mono.Unix.Catalog.GetString("Añadir Habitacion");
			this.fixed2.Add(this.btnAñadirHab);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnAñadirHab]));
			w5.X = 32;
			w5.Y = 125;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnEliminarHab = new global::Gtk.Button();
			this.btnEliminarHab.CanFocus = true;
			this.btnEliminarHab.Name = "btnEliminarHab";
			this.btnEliminarHab.UseUnderline = true;
			this.btnEliminarHab.Label = global::Mono.Unix.Catalog.GetString("Eliminar Habitacion");
			this.fixed2.Add(this.btnEliminarHab);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnEliminarHab]));
			w6.X = 200;
			w6.Y = 125;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed2.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnBuscar]));
			w7.X = 280;
			w7.Y = 170;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.vwTablaHab = new global::Gtk.ScrolledWindow();
			this.vwTablaHab.WidthRequest = 350;
			this.vwTablaHab.HeightRequest = 380;
			this.vwTablaHab.Name = "vwTablaHab";
			this.vwTablaHab.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child vwTablaHab.Gtk.Container+ContainerChild
			this.tvwHabitaciones = new global::Gtk.TreeView();
			this.tvwHabitaciones.CanFocus = true;
			this.tvwHabitaciones.Name = "tvwHabitaciones";
			this.vwTablaHab.Add(this.tvwHabitaciones);
			this.fixed2.Add(this.vwTablaHab);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.vwTablaHab]));
			w9.X = 24;
			w9.Y = 210;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxDescripcHab = global::Gtk.ComboBox.NewText();
			this.cbxDescripcHab.WidthRequest = 160;
			this.cbxDescripcHab.Name = "cbxDescripcHab";
			this.fixed2.Add(this.cbxDescripcHab);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxDescripcHab]));
			w10.X = 194;
			w10.Y = 85;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.WidthChars = 30;
			this.txtBuscar.InvisibleChar = '•';
			this.fixed2.Add(this.txtBuscar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtBuscar]));
			w11.X = 29;
			w11.Y = 171;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 610;
			this.Show();
			//this.btnAñadirHab.Clicked += new global::System.EventHandler(this.OnBtnAñadirHabClicked);
			//this.btnEliminarHab.Clicked += new global::System.EventHandler(this.OnBtnEliminarHabClicked);
			//this.btnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
			//this.tvwHabitaciones.CursorChanged += new global::System.EventHandler(this.OnTvwHabitacionesCursorChanged);
		}
	}
}
