
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frm_reservaciones
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtBuscar;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView twReserv;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnFinalizar;

		private global::Gtk.Button btnNuevo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frm_reservaciones
			this.Name = "Hotel.frm_reservaciones";
			this.Title = global::Mono.Unix.Catalog.GetString("frm_reservaciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Hotel.frm_reservaciones.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 300;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w1.X = 83;
			w1.Y = 102;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w2.X = 433;
			w2.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.WidthRequest = 190;
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscar]));
			w3.X = 501;
			w3.Y = 120;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.twReserv = new global::Gtk.TreeView();
			this.twReserv.WidthRequest = 370;
			this.twReserv.HeightRequest = 330;
			this.twReserv.CanFocus = true;
			this.twReserv.Name = "twReserv";
			this.GtkScrolledWindow.Add(this.twReserv);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w5.X = 11;
			w5.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("RESERVACIONES");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w6.X = 337;
			w6.Y = 19;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 120;
			this.btnBuscar.HeightRequest = 30;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnBuscar]));
			w7.X = 528;
			w7.Y = 162;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.WidthRequest = 120;
			this.btnModificar.HeightRequest = 30;
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed1.Add(this.btnModificar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnModificar]));
			w8.X = 425;
			w8.Y = 230;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnFinalizar = new global::Gtk.Button();
			this.btnFinalizar.WidthRequest = 120;
			this.btnFinalizar.HeightRequest = 30;
			this.btnFinalizar.CanFocus = true;
			this.btnFinalizar.Name = "btnFinalizar";
			this.btnFinalizar.UseUnderline = true;
			this.btnFinalizar.Label = global::Mono.Unix.Catalog.GetString("Finalizar");
			this.fixed1.Add(this.btnFinalizar);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnFinalizar]));
			w9.X = 427;
			w9.Y = 285;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.WidthRequest = 120;
			this.btnNuevo.HeightRequest = 30;
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.fixed1.Add(this.btnNuevo);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnNuevo]));
			w10.X = 428;
			w10.Y = 336;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 792;
			this.DefaultHeight = 478;
			this.Show();
		}
	}
}
