
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frm_EmisorTarjeta
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry txtEmisor;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.ComboBox cbxEmisores;

		private global::Gtk.Label label1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frm_EmisorTarjeta
			this.Name = "Hotel.frm_EmisorTarjeta";
			this.Title = global::Mono.Unix.Catalog.GetString("frm_EmisorTarjeta");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Hotel.frm_EmisorTarjeta.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtEmisor = new global::Gtk.Entry();
			this.txtEmisor.CanFocus = true;
			this.txtEmisor.Name = "txtEmisor";
			this.txtEmisor.IsEditable = true;
			this.txtEmisor.InvisibleChar = '•';
			this.fixed1.Add(this.txtEmisor);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtEmisor]));
			w1.X = 68;
			w1.Y = 107;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.WidthRequest = 80;
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.fixed1.Add(this.btnAgregar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAgregar]));
			w2.X = 251;
			w2.Y = 108;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.WidthRequest = 80;
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.fixed1.Add(this.btnEditar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEditar]));
			w3.X = 252;
			w3.Y = 166;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.WidthRequest = 80;
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w4.X = 342;
			w4.Y = 166;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxEmisores = global::Gtk.ComboBox.NewText();
			this.cbxEmisores.WidthRequest = 160;
			this.cbxEmisores.Name = "cbxEmisores";
			this.fixed1.Add(this.cbxEmisores);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxEmisores]));
			w5.X = 67;
			w5.Y = 163;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Emisores de tarjetas");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w6.X = 69;
			w6.Y = 48;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 486;
			this.DefaultHeight = 428;
			this.Show();
			this.btnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
			this.btnEditar.Clicked += new global::System.EventHandler(this.OnBtnEditarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
		}
	}
}
