
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class frm_huespedReserv
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtNombres;

		private global::Gtk.Entry txtApellidos;

		private global::Gtk.Entry txtCedula;

		private global::Gtk.Label label4;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView twHuesped;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Entry txtBuscar;

		private global::Gtk.Button btnBuscar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.frm_huespedReserv
			this.Name = "Hotel.frm_huespedReserv";
			this.Title = global::Mono.Unix.Catalog.GetString("frm_huespedReserv");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child Hotel.frm_huespedReserv.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ESCOGER HUÉSPED");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w1.X = 256;
			w1.Y = 22;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w2.X = 29;
			w2.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombres = new global::Gtk.Entry();
			this.txtNombres.WidthRequest = 180;
			this.txtNombres.CanFocus = true;
			this.txtNombres.Name = "txtNombres";
			this.txtNombres.IsEditable = false;
			this.txtNombres.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombres);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombres]));
			w3.X = 124;
			w3.Y = 70;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtApellidos = new global::Gtk.Entry();
			this.txtApellidos.WidthRequest = 180;
			this.txtApellidos.CanFocus = true;
			this.txtApellidos.Name = "txtApellidos";
			this.txtApellidos.IsEditable = false;
			this.txtApellidos.InvisibleChar = '•';
			this.fixed1.Add(this.txtApellidos);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtApellidos]));
			w4.X = 124;
			w4.Y = 106;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCedula = new global::Gtk.Entry();
			this.txtCedula.WidthRequest = 180;
			this.txtCedula.CanFocus = true;
			this.txtCedula.Name = "txtCedula";
			this.txtCedula.IsEditable = false;
			this.txtCedula.InvisibleChar = '•';
			this.fixed1.Add(this.txtCedula);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCedula]));
			w5.X = 124;
			w5.Y = 143;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Cédula:");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w6.X = 29;
			w6.Y = 146;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos: ");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w7.X = 29;
			w7.Y = 110;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.twHuesped = new global::Gtk.TreeView();
			this.twHuesped.WidthRequest = 370;
			this.twHuesped.HeightRequest = 220;
			this.twHuesped.CanFocus = true;
			this.twHuesped.Name = "twHuesped";
			this.GtkScrolledWindow.Add(this.twHuesped);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w9.X = 29;
			w9.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.WidthRequest = 90;
			this.btnCancelar.HeightRequest = 30;
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancelar]));
			w10.X = 468;
			w10.Y = 385;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.WidthRequest = 90;
			this.btnAgregar.HeightRequest = 30;
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.fixed1.Add(this.btnAgregar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAgregar]));
			w11.X = 471;
			w11.Y = 307;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.WidthRequest = 250;
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscar);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscar]));
			w12.X = 29;
			w12.Y = 195;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 100;
			this.btnBuscar.HeightRequest = 30;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnBuscar]));
			w13.X = 297;
			w13.Y = 193;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 651;
			this.DefaultHeight = 504;
			this.Show();
			this.twHuesped.CursorChanged += new global::System.EventHandler(this.OnTwHuespedCursorChanged);
			this.btnCancelar.Clicked += new global::System.EventHandler(this.OnBtnCancelarClicked);
			this.btnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
			this.btnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
		}
	}
}
