
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel.datos
{
	public partial class dtTipoHabitaciones
	{
		public virtual void Build()
		{
			// Action group Hotel.datos.dtTipoHabitaciones
		}
	}
}
