
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class fmr_Reservacion
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lbl_titulo;

		private global::Gtk.Entry txtNum;

		private global::Gtk.Label lbl_numReserv;

		private global::Gtk.ToggleButton btn_elegirHuesped;

		private global::Gtk.Calendar calendar2;

		private global::Gtk.Label lbHuesped;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview3;

		private global::Gtk.ComboBoxEntry comboboxentry2;

		private global::Gtk.ToggleButton btn_agregarHab;

		private global::Gtk.ToggleButton btn_removerHab;

		private global::Gtk.Button button10;

		private global::Gtk.Button button11;

		private global::Gtk.Button button12;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.fmr_Reservacion
			this.Name = "Hotel.fmr_Reservacion";
			this.Title = global::Mono.Unix.Catalog.GetString("fmr_Reservacion");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child Hotel.fmr_Reservacion.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbl_titulo = new global::Gtk.Label();
			this.lbl_titulo.Name = "lbl_titulo";
			this.lbl_titulo.LabelProp = global::Mono.Unix.Catalog.GetString("REGISTRAR RESERVACION");
			this.fixed1.Add(this.lbl_titulo);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbl_titulo]));
			w1.X = 287;
			w1.Y = 25;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNum = new global::Gtk.Entry();
			this.txtNum.CanFocus = true;
			this.txtNum.Name = "txtNum";
			this.txtNum.IsEditable = false;
			this.txtNum.InvisibleChar = '•';
			this.fixed1.Add(this.txtNum);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNum]));
			w2.X = 136;
			w2.Y = 92;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbl_numReserv = new global::Gtk.Label();
			this.lbl_numReserv.Name = "lbl_numReserv";
			this.lbl_numReserv.LabelProp = global::Mono.Unix.Catalog.GetString("Reservacion:");
			this.fixed1.Add(this.lbl_numReserv);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbl_numReserv]));
			w3.X = 29;
			w3.Y = 95;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btn_elegirHuesped = new global::Gtk.ToggleButton();
			this.btn_elegirHuesped.CanFocus = true;
			this.btn_elegirHuesped.Name = "btn_elegirHuesped";
			this.btn_elegirHuesped.UseUnderline = true;
			this.btn_elegirHuesped.Active = true;
			this.btn_elegirHuesped.Label = global::Mono.Unix.Catalog.GetString("Elegir Huesped");
			this.fixed1.Add(this.btn_elegirHuesped);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_elegirHuesped]));
			w4.X = 22;
			w4.Y = 145;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar2 = new global::Gtk.Calendar();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar2]));
			w5.X = 440;
			w5.Y = 79;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbHuesped = new global::Gtk.Label();
			this.lbHuesped.Name = "lbHuesped";
			this.lbHuesped.LabelProp = global::Mono.Unix.Catalog.GetString("Huésped: XXXXXX");
			this.fixed1.Add(this.lbHuesped);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbHuesped]));
			w6.X = 168;
			w6.Y = 152;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView();
			this.treeview3.WidthRequest = 300;
			this.treeview3.HeightRequest = 200;
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.GtkScrolledWindow.Add(this.treeview3);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w8.X = 28;
			w8.Y = 253;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry2.Name = "comboboxentry2";
			this.fixed1.Add(this.comboboxentry2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboboxentry2]));
			w9.X = 27;
			w9.Y = 212;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btn_agregarHab = new global::Gtk.ToggleButton();
			this.btn_agregarHab.CanFocus = true;
			this.btn_agregarHab.Name = "btn_agregarHab";
			this.btn_agregarHab.UseUnderline = true;
			this.btn_agregarHab.Label = global::Mono.Unix.Catalog.GetString("Agregar habitación");
			this.fixed1.Add(this.btn_agregarHab);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_agregarHab]));
			w10.X = 437;
			w10.Y = 317;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btn_removerHab = new global::Gtk.ToggleButton();
			this.btn_removerHab.CanFocus = true;
			this.btn_removerHab.Name = "btn_removerHab";
			this.btn_removerHab.UseUnderline = true;
			this.btn_removerHab.Label = global::Mono.Unix.Catalog.GetString("Remover habitación");
			this.fixed1.Add(this.btn_removerHab);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_removerHab]));
			w11.X = 437;
			w11.Y = 363;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Facturar");
			this.fixed1.Add(this.button10);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button10]));
			w12.X = 438;
			w12.Y = 429;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.button11);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button11]));
			w13.X = 525;
			w13.Y = 429;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.button12);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button12]));
			w14.X = 606;
			w14.Y = 428;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 834;
			this.DefaultHeight = 553;
			this.Show();
			this.btn_elegirHuesped.Clicked += new global::System.EventHandler(this.OnBtnElegirHuespedClicked);
			this.btn_agregarHab.Clicked += new global::System.EventHandler(this.OnBtnAgregarHabClicked);
		}
	}
}
