
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class fmr_login
	{
		private global::Gtk.Fixed contenedor;

		private global::Gtk.Label label1;

		private global::Gtk.Label lbl_usuario;

		private global::Gtk.Label lbl_clave;

		private global::Gtk.Entry txt_usuario;

		private global::Gtk.Entry txt_clave;

		private global::Gtk.Button btn_ingresar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.fmr_login
			this.Name = "Hotel.fmr_login";
			this.Title = global::Mono.Unix.Catalog.GetString("Hotel");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 700;
			this.DefaultHeight = 500;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child Hotel.fmr_login.Gtk.Container+ContainerChild
			this.contenedor = new global::Gtk.Fixed();
			this.contenedor.Name = "contenedor";
			this.contenedor.HasWindow = false;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("BIENVENIDO USUARIO");
			this.contenedor.Add(this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.label1]));
			w1.X = 270;
			w1.Y = 59;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.lbl_usuario = new global::Gtk.Label();
			this.lbl_usuario.Name = "lbl_usuario";
			this.lbl_usuario.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario");
			this.contenedor.Add(this.lbl_usuario);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.lbl_usuario]));
			w2.X = 151;
			w2.Y = 128;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.lbl_clave = new global::Gtk.Label();
			this.lbl_clave.Name = "lbl_clave";
			this.lbl_clave.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña");
			this.contenedor.Add(this.lbl_clave);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.lbl_clave]));
			w3.X = 151;
			w3.Y = 182;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.txt_usuario = new global::Gtk.Entry();
			this.txt_usuario.CanFocus = true;
			this.txt_usuario.Name = "txt_usuario";
			this.txt_usuario.IsEditable = true;
			this.txt_usuario.InvisibleChar = '•';
			this.contenedor.Add(this.txt_usuario);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.txt_usuario]));
			w4.X = 266;
			w4.Y = 125;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.txt_clave = new global::Gtk.Entry();
			this.txt_clave.CanFocus = true;
			this.txt_clave.Name = "txt_clave";
			this.txt_clave.IsEditable = true;
			this.txt_clave.Visibility = false;
			this.txt_clave.InvisibleChar = '•';
			this.contenedor.Add(this.txt_clave);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.txt_clave]));
			w5.X = 266;
			w5.Y = 175;
			// Container child contenedor.Gtk.Fixed+FixedChild
			this.btn_ingresar = new global::Gtk.Button();
			this.btn_ingresar.WidthRequest = 120;
			this.btn_ingresar.HeightRequest = 40;
			this.btn_ingresar.CanFocus = true;
			this.btn_ingresar.Name = "btn_ingresar";
			this.btn_ingresar.UseUnderline = true;
			this.btn_ingresar.Label = global::Mono.Unix.Catalog.GetString("Ingresar");
			this.contenedor.Add(this.btn_ingresar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.contenedor[this.btn_ingresar]));
			w6.X = 293;
			w6.Y = 245;
			this.Add(this.contenedor);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.btn_ingresar.Clicked += new global::System.EventHandler(this.OnBtnIngresarClicked);
		}
	}
}
