
// This file has been generated by the GUI designer. Do not modify.
namespace Hotel
{
	public partial class fmrGestionHabitaciones
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Hotel.fmrGestionHabitaciones
			this.Name = "Hotel.fmrGestionHabitaciones";
			this.Title = global::Mono.Unix.Catalog.GetString("fmrGestionHabitaciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
